

name: publiceren naar WOOSETUP

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ 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.API_TOKEN_GITHUB }}
      with:
        source_file: 'docs/'
        destination_repo: 'Vincentvandijk96/WOO'
        destination_folder: 'docs/'
        user_email: 'vincentvandijkprive@gmail.com'
        user_name: 'Vincentvandijk96'
        commit_message: 'publicatie'

