        
name: Kopieer docs-map naar bestemmingsrepository

on:
  push:
    branches:
      - main

jobs:
  copy_docs_map:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout bronrepository
        uses: actions/checkout@v2

      - name: Verwijder docs-map in bestemmingsrepository
        run: |
          git clone https://github.com/Vincentvandijk96/WOO.git
          cd WOO
          rm -rf docs

      - name: Kopieer docs-map naar bestemmingsrepository
        run: |
          cp -r ../WOOSETUP/docs ../WOO

      - name: Commit en push wijzigingen naar bestemmingsrepository
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Vincentvandijk96
          author_email: Vincentvandijkprive@gmail.com
          message: Kopieer docs-map naar bestemmingsrepository
          add: 'docs'
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
