name: Publish docs to WOO
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Empty WOO/docs
        run: |
          rm -rf $GITHUB_WORKSPACE/WOO/docs/*
      - name: Copy docs to WOO
        run: |
          cp -r $GITHUB_WORKSPACE/docs/* $GITHUB_WORKSPACE/WOO/docs

      - name: Push to WOO
        run: |
          git add $GITHUB_WORKSPACE/WOO/docs
          git commit -m "Publish docs"
          git push
          
          

