name: Copy Docs to Destination

on:
  push:
    branches:
      - main

jobs:
  copy_docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: Vincentvandijk96/WOOSETUP
          
      - name: Set up destination repository
        env:
          DESTINATION_TOKEN: ${{ secrets.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 }}
        run: |
          git remote set-url origin "https://x-access-token:${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}@github.com/Vincentvandijk96/WOO.git"
          
      - name: Remove 'docs' directory in destination repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone https://github.com/Vincentvandijk96/WOO.git
          cd WOO
          git rm -r docs
          git commit -m "Remove 'docs' directory"
          git push origin main
          
      - name: Copy 'docs' directory to destination repository
        run: |
          git clone https://github.com/Vincentvandijk96/WOOSETUP.git
          cd WOOSETUP
          cp -r docs/ ../WOO/
          cd ../WOO
          git add .
          git commit -m "Copy 'docs' directory"
          git push origin main
