name: Copy docs folder
on:
  push:
    branches:
      - main
jobs:
  copy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: Vincentvandijk96/WOO
          ref: main
      - run: |
          echo "Deleting all contents of docs folder in remote repository..."
          rm -rf <remote-repository>/docs
          echo "Copying contents of docs folder from current repository to remote repository..."
          cp -r docs/ WOO/docs
