name: Sync Docs

on:
  push:
    branches:
      - main

jobs:
  sync-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: Vincentvandijk96/WOO
          ref: main

      - name: Remove Docs Folder
        run: rm -rf docs

      - name: Copy Docs Folder
        run: cp -r docs/. Vincentvandijk96/WOO/docs
